# Generated by Django 4.1.3 on 2023-02-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submitAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Enter First Name', max_length=200)),
                ('lname', models.CharField(default='Enter Last Name', max_length=200)),
                ('stud_id', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('attend', models.IntegerField(choices=[(None, '----------'), (2, 'Present'), (1, 'Late'), (0, 'Absent')], default=0)),
            ],
        ),
    ]
