# Generated by Django 4.2 on 2023-03-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitattendance',
            name='attend',
        ),
        migrations.AddField(
            model_name='submitattendance',
            name='reason',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
