# Generated by Django 3.0 on 2023-03-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_submitattendance_attend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitattendance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
