# Generated by Django 4.1.7 on 2023-03-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20230319_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
