# Generated by Django 4.1.3 on 2023-01-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstevaluation',
            name='student_id',
            field=models.IntegerField(default=1),
        ),
    ]
