# Generated by Django 4.2 on 2023-01-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0003_alter_firstevaluation_student_id_firstquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstquestions',
            name='firstEvaluation',
        ),
        migrations.AddField(
            model_name='firstquestions',
            name='first_name',
            field=models.CharField(default='enter_a_first_name', max_length=200),
        ),
        migrations.AddField(
            model_name='firstquestions',
            name='last_name',
            field=models.CharField(default='enter_a_last_name', max_length=200),
        ),
        migrations.AddField(
            model_name='firstquestions',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
