# Generated by Django 4.1.3 on 2023-01-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0005_alter_firstquestions_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='firstQuestions',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='student_id',
            new_name='stud_id',
        ),
        migrations.RemoveField(
            model_name='firstevaluation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='firstevaluation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='firstevaluation',
            name='fname',
            field=models.CharField(default='Enter First Name', max_length=200),
        ),
        migrations.AddField(
            model_name='firstevaluation',
            name='lname',
            field=models.CharField(default='Enter Last Name', max_length=200),
        ),
        migrations.AddField(
            model_name='firstevaluation',
            name='question1a',
            field=models.IntegerField(choices=[(0, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
    ]
