# Generated by Django 4.1.3 on 2023-01-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0007_firstevaluation_comment_firstevaluation_question1b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstevaluation',
            name='question1a',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question1b',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question1c',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question1d',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question2e',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question2f',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question2g',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question2h',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question2i',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question3j',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question3k',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question3l',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question4m',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question5a',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question5b',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question5c',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question5d',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question5e',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question6f',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question6g',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='question7h',
            field=models.IntegerField(choices=[(None, '----------'), (3, 'Exceeds Expectations'), (2, 'Meets Expectations'), (1, 'Emerging'), (0, 'Does Not Meet Expectations')], default=0),
        ),
    ]
