# Generated by Django 4.1.3 on 2023-03-14 23:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evalFirst', '0009_firstevaluation_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstevaluation',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.DO_NOTHING, related_name='firstEvaluation', to=settings.AUTH_USER_MODEL),
        ),
    ]
