# Generated by Django 4.2 on 2023-03-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0010_alter_firstevaluation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_ID',
            field=models.IntegerField(default=0),
        ),
    ]
