# Generated by Django 4.2 on 2023-03-19 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evalFirst', '0011_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstevaluation',
            name='user',
            field=models.ForeignKey(default=models.IntegerField(default=0), on_delete=django.db.models.deletion.DO_NOTHING, related_name='firstEvaluation', to=settings.AUTH_USER_MODEL),
        ),
    ]
