# Generated by Django 4.1.7 on 2023-03-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0013_alter_firstevaluation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstevaluation',
            name='fname',
            field=models.CharField(db_column='First Name', default='Enter First Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='lname',
            field=models.CharField(db_column='Last Name', default='Enter Last Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='firstevaluation',
            name='stud_id',
            field=models.IntegerField(db_column='Student ID', default=0),
        ),
    ]
