# Generated by Django 4.2 on 2023-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0014_alter_firstevaluation_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_admin',
            field=models.IntegerField(default=0),
        ),
    ]
