# Generated by Django 4.1.7 on 2023-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0015_profile_temp_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstevaluation',
            name='EvaluationNum',
            field=models.IntegerField(choices=[(0, '----------'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
    ]
