# Generated by Django 4.1.7 on 2023-03-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalFirst', '0018_rename_evaluationnum_firstevaluation_evaluation_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question1a',
            new_name='Pedagogy_A',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question1b',
            new_name='Pedagogy_B',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question1c',
            new_name='Pedagogy_C',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question1d',
            new_name='Pedagogy_D',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question2e',
            new_name='Pedagogy_E',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question2f',
            new_name='Pedagogy_F',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question2g',
            new_name='Pedagogy_G',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question2h',
            new_name='Pedagogy_H',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question2i',
            new_name='Pedagogy_I',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question3j',
            new_name='Pedagogy_J',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question3k',
            new_name='Pedagogy_K',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question3l',
            new_name='Pedagogy_L',
        ),
        migrations.RenameField(
            model_name='firstevaluation',
            old_name='question4m',
            new_name='Pedagogy_M',
        ),
    ]
